In [3]:
# 1. What is a Python library? Why ^o we use Python libraries?
#A Python library is a collection of pre-written code that provides functionality to perform specific tasks or solve certain problems. These libraries contain modules, functions, classes, and constants that can be imported and used in your Python programs.

In [4]:
# 2. What is the ^ifference between Numpy array an^ List?
## NumPy arrays and Python lists are both used to store collections of data, but they have several differences:

#1. Data Type: In Python lists, elements can be of different data types (e.g., integers, strings, lists, etc.). However, NumPy arrays are homogeneous, meaning all elements must be of the same data type. This homogeneity allows for more efficient storage and operations on NumPy arrays.

##2. Performance: NumPy arrays are more efficient than Python lists for numerical operations, especially for large datasets. NumPy arrays are implemented in C and are optimized for performance, whereas Python lists are more flexible but slower due to their dynamic nature.

#3. Memory Efficiency: NumPy arrays consume less memory compared to Python lists, primarily because NumPy arrays are stored in contiguous memory blocks, whereas Python lists are arrays of pointers to objects stored elsewhere in memory.

#4. Functionality: NumPy arrays provide a wide range of mathematical functions and operations optimized for array-based computing, such as element-wise operations, matrix multiplication, statistical functions, and linear algebra operations. Python lists offer general-purpose functionality but lack the specialized numerical capabilities of NumPy arrays.

#5. Indexing and Slicing: Both NumPy arrays and Python lists support indexing and slicing, but NumPy arrays offer more advanced indexing techniques, such as boolean indexing, fancy indexing, and multidimensional slicing.



In [5]:
# 3. Fin^ the shape, size an^ ^imension of the following array?

import numpy as np


arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

shape = arr.shape
size = arr.size
dimensions = arr.ndim

print("Shape of the array:", shape)
print("Size of the array:", size)
print("Dimensions of the array:", dimensions)


Shape of the array: (3, 4)
Size of the array: 12
Dimensions of the array: 2


In [6]:
# 4. Write python co^e to access the first row of the following array?

import numpy as np

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

first_row = arr[0]


print("First row of the array:", first_row)


First row of the array: [1 2 3 4]


In [7]:
# 5. How ^o you access the element at the thir^ row an^ fourth column from the given numpy array?

import numpy as np


arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])


element = arr[2, 3]

print("Element at the third row and fourth column:", element)


Element at the third row and fourth column: 12


In [8]:
## 6. Write co^e to extract all o^^-in^exe^ elements from the given numpy array?

import numpy as np


arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

odd_indexed_elements = arr[:, 1::2]

print("Odd-indexed elements from the array:")
print(odd_indexed_elements)


Odd-indexed elements from the array:
[[ 2  4]
 [ 6  8]
 [10 12]]


In [9]:
## 7. How can you generate a ran^om 3x3 matrix with values between 0 an^ 1?

import numpy as np

random_matrix = np.random.random((3, 3))

print("Random 3x3 matrix with values between 0 and 1:")
print(random_matrix)


Random 3x3 matrix with values between 0 and 1:
[[0.02097671 0.81880643 0.87193058]
 [0.08572989 0.33078497 0.98389441]
 [0.24722188 0.19692073 0.29141406]]


In [10]:
## 8. Describe the ^ifference between np.ran^om.ran^ an^ np.ran^om.ran^n?

# 1. np.random.rand:
#    This function generates random numbers from a uniform distribution over the interval [0, 1).
#    Each number in the output array is sampled independently and uniformly from the interval [0, 1).
#    The shape of the output array is determined by the arguments passed to the function.

# 2. np.random.randn:
#    This function generates random numbers from a standard normal distribution (mean = 0, standard deviation = 1).
#   The numbers produced by `np.random.randn` follow a bell-shaped curve centered around 0, with the majority of values closer to 0 and tapering off towards the extremes.
#    Unlike `np.random.rand`, `np.random.randn` takes the dimensions of the desired output array as individual arguments, rather than a tuple representing the shape.



In [11]:
## 9. Write co^e to increase the ^imension of the following array?

import numpy as np

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])


increased_dimension_array = arr.reshape(3, 4, 1)


print("Array with increased dimension:")
print(increased_dimension_array)


Array with increased dimension:
[[[ 1]
  [ 2]
  [ 3]
  [ 4]]

 [[ 5]
  [ 6]
  [ 7]
  [ 8]]

 [[ 9]
  [10]
  [11]
  [12]]]


In [12]:
## 10. How to transpose the following array in NumPy?

import numpy as np


arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

transposed_array = np.transpose(arr)

print("Transposed array:")
print(transposed_array)


Transposed array:
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [13]:
# ##11. Consi^er the following matrix:
# Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
# Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

# Perform the following operation using Python1
# Index wiLe multiplicatio'
# Martix multiplicatio'
# Additionboth the maticK
# Subtraction matix B om
# DivideMatix B by A

import numpy as np

# Define matrices A2 and B2 as NumPy arrays
A2 = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])

B2 = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])

# Element-wise multiplication
element_wise_multiplication = A2 * B2

# Matrix multiplication
matrix_multiplication = np.dot(A2, B2.T)

# Addition of both matrices
addition = A2 + B2

# Subtraction of matrix B2 from matrix A2
subtraction = A2 - B2

# Division of matrix B2 by matrix A2
division = np.divide(B2, A2)

# Print the results
print("Element-wise multiplication:")
print(element_wise_multiplication)

print("\nMatrix multiplication:")
print(matrix_multiplication)

print("\nAddition of both matrices:")
print(addition)

print("\nSubtraction of matrix B2 from matrix A2:")
print(subtraction)

print("\nDivision of matrix B2 by matrix A2:")
print(division)


Element-wise multiplication:
[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]

Matrix multiplication:
[[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]

Addition of both matrices:
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]

Subtraction of matrix B2 from matrix A2:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

Division of matrix B2 by matrix A2:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [14]:
## 12. Which function in Numpy can be use^ to swap the byte or^er of an array?

import numpy as np


arr = np.array([1, 256, 65536], dtype=np.int32)

# Swap the byte order of the array
swapped_arr = arr.byteswap()

# Print the original and swapped arrays
print("Original array:", arr)
print("Swapped array:", swapped_arr)


Original array: [    1   256 65536]
Swapped array: [16777216    65536      256]


In [15]:
# 13. What is the significance of the np.linalg.inv function?

# The np.linalg.inv function in NumPy is used to compute the multiplicative inverse of a square matrix. The significance of this function lies in its application in solving systems of linear equations, particularly in linear algebra.


In [16]:
## 14. What ^oes the np.reshape function ^o, an^ how is it use^?
import numpy as np


arr = np.array([1, 2, 3, 4, 5, 6])


reshaped_arr = np.reshape(arr, (2, 3))


print("Original array:")
print(arr)
print("\nReshaped array:")
print(reshaped_arr)


Original array:
[1 2 3 4 5 6]

Reshaped array:
[[1 2 3]
 [4 5 6]]


In [17]:
# 15. What is broa^casting in Numpy?

# Broadcasting in NumPy is a mechanism that allows arrays with different shapes to be combined together in arithmetic operations. It's a powerful feature that simplifies array operations and makes code more concise and readable.

import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])


B = np.array([10, 20, 30])

result = A + B


print(result)


[[11 22 33]
 [14 25 36]
 [17 28 39]]
